### ISSUE TITLE
Parameter 'zip_code' not found in 'ADDRESS' category for 'fr' locale

### ISSUE THREAD

**Issue by serpro69** [serpro69/kotlin-faker#138]
https://github.com/serpro69/kotlin-faker/blob/b128f4142fb78ad31aff5ad82793600c12be8740/core/src/main/resources/locales/fr/address.yml#L19-L20

**Comment by dariabajda** [comment]
That's a pity the issue is not described. :) 
Is it the same one that causes `Parameter 'street_prefix' not found in 'address' category` error for Polish locales? 

I've approached it when using: `faker.address.streetAddress()`
Link to Polish locales:
https://github.com/serpro69/kotlin-faker/blob/master/core/src/main/resources/locales/pl.yml#L17

**Comment by serpro69** [comment]
Hi @dariabajda ,

It could be similar, yes, but I'm not really sure how you're getting that error because `street_prefix` is there in the pl.yml file: https://github.com/serpro69/kotlin-faker/blob/5731ae67aef792d862cd8fef722b374d6fb23436/core/src/main/resources/locales/pl.yml?rgh-link-date=2022-07-11T14%3A54%3A08Z#L7 

Can you please open a separate issue for this and mention the version that you're using. Thanks.

**Comment by dariabajda** [comment]
Polish street name & address work like a charm in `1.12.0-rc.0`, thanks a lot! :)
