### ISSUE TITLE
Function areaCode not found

### ISSUE THREAD

**Issue by anefedov** [serpro69/kotlin-faker#172]
When using locale "en-US" getting `Function areaCode not found`

```
val config = fakerConfig { locale = "en-US" }
val phoneNumber = Faker(config).phoneNumber.cellPhone()
```

**Comment by anefedov** [comment]
I'm on [v1.13.0-rc.3](https://github.com/serpro69/kotlin-faker/releases/tag/v1.13.0-rc.3), but also tried 1.12.0 with the same result.
I was actually using `en` locale at first, but it's generating invalid US phone numbers. So I have to use `en-US`

**Comment by serpro69** [comment]
I see. I'll take a look at how this can be fixed. Probably some changes needed to `en-US.yml` file. Not an approach I like to (ab)use too much, since it becomes harder to merge changes to dictionaries later on from upstream, but I haven't found a better one on how to handle cases like this, where a localized dict has "functions" that don't exists in the default `en` locale.
