### ISSUE TITLE
(safe)Email sometimes creates invalid email addresses (for certain locales?)

### ISSUE THREAD

**Issue by martinvisser** [serpro69/kotlin-faker#174]
Sometimes we encountered emails that cannot be validated as valid email address when using `faker.internet.email()` or with `faker.internet.safeEmail()` when using certain locales, for example `nl-NL`.

I used [Valiktor](https://github.com/valiktor/valiktor) to test emails:

```kotlin
    @RepeatedTest(100)
    fun `test email validity`() {
        try {
            val email = Email(faker.internet.email())
            org.valiktor.validate(email) {
                validate(Email::value).isEmail()
            }
        } catch (e: ConstraintViolationException) {
            fail {
                val error = e.constraintViolations
                    .mapToMessage(baseName = "messages")
                    .associate { it.property to "${it.message}, but was '${it.value}'" }
                "Error: $error"
            }
        }
    }

    data class Email(val value: String) {
        init {
            validate(this) {
                validate(Email::value).isEmail()
            }
        }
    }
```

This generated email addresses like `jurriën.fleur@kpnmail.nl`, `msc.cil.ahmetović@hotmail.nl` and `chrisje.van.'t.leeuwis@kpnmail.nl`.

**Comment by serpro69** [comment]
Hi @martinvisser , thanks for raising the issue.
If I understand correctly, the issue for you is either `'` (or potentially other special chars) and/or accented letters? I'm not sure what rules the library you mention uses to validate emails, but IIRC what is allowed in the [RFC-2822](https://www.rfc-editor.org/rfc/rfc2822) for the local part (before the `@some.domain`) of the email address, then all of the email addresses you've posted here are valid.
Then again, email validation should be a very domain-specific thing, and from my experience, I don't think you generally want to conform to the RFC standards for email addresses, because frankly they allow very weird stuff.
Having your application targeted to users who live in Netherlands, for example, you might want to allow people to use accented characters in their names, such as `jurriën`, or you might not want to do that. That's up to you as an app developer, but RFC allows these chars, for example.

Now to what's actually causing this. The problem here is that an email is generated from a person's name (if you don't hardcode the name yourself of course):
https://github.com/serpro69/kotlin-faker/blob/f03e28b845611b7ddd70da99416c4114b94ca249/core/src/main/kotlin/io/github/serpro69/kfaker/provider/Internet.kt#L24
And since those names might contain special chars, for example see the first/last names in the `nl` locale dictionary file:
https://github.com/serpro69/kotlin-faker/blob/f03e28b845611b7ddd70da99416c4114b94ca249/core/src/main/resources/locales/nl.yml#L62
Then I don't see how to effectively solve this even if it made sense to do so, since it would need to be accounted for all supported locales, each possibly having its own "special letters".

So if you don't want special chars like `'` or accented letters like `ë` in your accepted email addresses, my suggestion would be to create a wrapper function that would replace them after the email has been generated, e.g.
```
fun normalizedEmail(): String {
    return faker.internet.email().replace("ë", "e")
}
```

A very crude example which can easily be expanded to cover all your specific cases.

**Comment by martinvisser** [comment]
Yeah, the RFC is super weird indeed. Thanks for the explanation though! I think the issue lies more at Valiktor's side then here, you have a good point there.
I'll close it with that reason.

**Comment by serpro69** [comment]
No problem. Hope faker is still useful for you in it's current form :) And feel free to open another issue if you find something not working as expected or need help with something.
