### ISSUE TITLE
faker.randomProvider.randomClassInstance() is not accessible

### ISSUE THREAD

**Issue by matteocodogno** [serpro69/kotlin-faker#18]
The method `randomClassInstance` is marked as an `internal` function, so it is impossible access to it from my code.

Am I missing something?

**Comment by serpro69** [comment]
Thanks for the issue @matteocodogno 

The proposed fix in the #21 won't work because inline functions can't access private ones, see here for more details: https://kotlinlang.org/docs/reference/inline-functions.html#public-inline-restrictions, hence the build fails with compilation error.

I'm adding a fix to this now.

**Comment by serpro69** [comment]
A new version with the fix is available on bintray: https://bintray.com/beta/#/serpro69/maven/kotlin-faker/1.1.1?tab=overview
