### ISSUE TITLE
RandomClassProvider doesn't handle constructorless types correctly in all instances

### ISSUE THREAD

**Issue by samcgardner** [serpro69/kotlin-faker#204]
`RandomClassProvider` has special handling for types like primitives and enums that don't have constructors. However, this special handling is only applied when mapping over direct constructor parameters. This means that constructor-less classes don't get built correctly if they are built under other circumstances, such as when they are included in a collection. For example:

```kotlin
package com.mr.reproducer

import io.github.serpro69.kfaker.Faker
import org.junit.jupiter.api.Test

data class Works(val case : AnEnum)

data class DoesNotWork(val case : List<AnEnum>)

enum class AnEnum {
    FOO,
    BAR
}

class TestCases {

    @Test
    fun `special handling occurs`() {
        Faker().randomProvider.randomClassInstance<Works>()
    }

    @Test
    fun `special handling does not occur`() {
        Faker().randomProvider.randomClassInstance<DoesNotWork>()
    }
}
```

Although I provide one specific way to reproduce this issue, anything that calls `randomClassInstance` can hit this bug. I believe this class of error could be handled for all cases by checking for constructorless cases at the top of `randomClassInstance`, but I haven't studied this question in detail.

If you're open to reviewing a pull request I'd be happy to submit one, but in either case thank you for your work on this project!

**Comment by serpro69** [comment]
Hi @samcgardner , 
Thanks for opening this issue!

Yes, you're correct, the above case is broken. This is because an enum doesn't have a constructor as such, so when an enum is a type of a collection - it will fail, particularly in this part https://github.com/serpro69/kotlin-faker/blob/2a41e3ade343a9a32bd15800ba8944830a958574/core/src/main/kotlin/io/github/serpro69/kfaker/provider/misc/RandomClassProvider.kt#L133-L149

The fix should be pretty simple I think. For example, if no constructors are found, we can check if the receiver is an enum or not, and then call randomEnumOrNull on the receiver.

I'm always open to PRs that fix issues :) If you want do that - please feel free to open a PR. Otherwise I can take a look at fixing this myself. Just let me know how you want to proceed.
