### ISSUE TITLE
Suggestion: internet.ipv4() and internet.ipv6()

### ISSUE THREAD

**Issue by axelfontaine** [serpro69/kotlin-faker#211]
In the usual String formats

**Comment by serpro69** [comment]
Huh, weird it's not there already.

Feel free to add this if you like :) 
But unless it's available in the yml of the upstream ruby-faker, I think it's better to generate the values inside a function directly instead of adding custom stuff to a yml file. The latter makes it harder to pull and merge changes to these dictionary files.

**Comment by axelfontaine** [comment]
It looks like they have it upstream: https://www.rubydoc.info/gems/faker/Faker/Internet#ip_v4_address-class_method

**Comment by serpro69** [comment]
Yep, but also implemented the way I suggested above , and not via .yml file: https://github.com/faker-ruby/faker/blob/d355cc3ed6767c118729039839e2d7666c49ee56/lib/faker/default/internet.rb#L279-L280

This makes sense also, because this way it's way easier to exclude invalid values in the ip range.

**Comment by serpro69** [comment]
We could even take this a bit further. 
E.g. generating a random address for a given network/mask could potentially be useful? Generating a random address in the same subnet as supplied address as well maybe?
