### ISSUE TITLE
Ques: Random money amount

### ISSUE THREAD

**Issue by kdani41** [serpro69/kotlin-faker#59]
Thanks for this amazing library. 
Is there any way to generate random dollar amount as string?

**Comment by serpro69** [comment]
Hi.
Can you give an example of what function you are calling and what output you expect?

**Comment by kdani41** [comment]
Some function that can help creating random amount.

So is something like this possible?
```
faker.amount(Locale.US) - $123,312,123

**Comment by serpro69** [comment]
Take a look at [RandomService](https://github.com/serpro69/kotlin-faker/blob/master/core/src/main/kotlin/io/github/serpro69/kfaker/RandomService.kt) class. Initially I didn't think it would be useful to have it public since mostly what it does is wrapping around `java.util.Random`. But I don't see any reason not to expose it from `Faker` class, for example, if it can be useful.

You could do something like:
```
val intAmount = faker.randomService.nextInt(1, 100) // returns a random int from 1 to 100
val moneyAmount = "$$intAmount"
```

Different monetary signs like `$`, `€`, `¥`, et al., can be supported through a separate function if that's of any interest as well.

**Comment by kdani41** [comment]
Thanks for this but i think I will have to end up using a currency formatter that formats the value correctly because in the end the result should look something like this `$125,212,12.04`

**Comment by serpro69** [comment]
A random number with a floating point can also be generated by `RandomService` class.
But from what I understood, you also need a "thousands separator" (in your example it's a `,`  but I think it should be configurable as well) ?
In that case a new function can be added (probably to [Finance](https://github.com/serpro69/kotlin-faker/blob/master/core/src/main/kotlin/io/github/serpro69/kfaker/provider/Finance.kt) provider, unless I find a better place for it), that puts all of this together.

**Comment by serpro69** [comment]
Closed with https://github.com/serpro69/kotlin-faker/commit/2e3daea2e3ffb3e618872838e2efa534d9c82cb2

@kdani41 FYI.
