### ISSUE TITLE
Generating random Double, Int or Float?

### ISSUE THREAD

**Issue by johanvergeer** [serpro69/kotlin-faker#67]
I'm probably missing the obvious, but I've been looking for a way to generate a random `Double`, `Int` or `Float` with `kotlin-faker` and I haven't been able to find it. 

Is there a way to generate these values with `kotlin-faker` or should the builtin `Random` class be used for these values?

I did see [this post](https://github.com/serpro69/kotlin-faker/issues/59#issuecomment-761040887) which uses `faker.randomService.nextInt(1, 100)`, but that doesn't seem to be available. 

I'm using Kotlin 1.5.0, kotlin-faker 1.7.1 and kotest 4.4.3

**Comment by serpro69** [comment]
Hi @johanvergeer ,

`RandomService` has `internal` visibility because I didn't see how it would be useful to expose it to the world - after all 90% of it just wraps around `java.util.Random` functions. But seeing that this is the second time a similar request comes to make it publicly visible - I don't see an issue in doing that. I will include this in the next release.

**Comment by johanvergeer** [comment]
That would be very nice indeed. That way we have a single interface for generating random values.

**Comment by serpro69** [comment]
@johanvergeer , this is now available in latest `1.7.2-SNAPSHOT` version.
The functionality is exposed through `random` property in the `Faker` class.
Please refer to [downloading](https://github.com/serpro69/kotlin-faker#downloading) section of the readme on how to enable snapshots if you don't want to wait until it gets into a stable release.

**Comment by johanvergeer** [comment]
Thanks @serpro69 I'll give it a shot.
